name: Swagger json build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 20.x
      uses: actions/setup-node@v1
      with:
        node-version: 20.x
    - run: npm install @openapitools/openapi-generator-cli -g
    - run: openapi-generator-cli generate -i ./spec/auth-api.v1.0.yaml -g openapi -o build-auth
    - run: openapi-generator-cli generate -i ./spec/compute-api.v1.0.yaml -g openapi -o build-compute
    - run: openapi-generator-cli generate -i ./spec/domain-api.v1.0.yaml -g openapi -o build-domain
    - run: openapi-generator-cli generate -i ./spec/billing-api.v1.0.yaml -g openapi -o build-billing
    - run: openapi-generator-cli generate -i ./spec/addon-api.v1.0.yaml -g openapi -o build-addon
    - run: mkdir build
    - run: mv build-auth/openapi.json build/auth-openapi.json
    - run: mv build-compute/openapi.json build/compute-openapi.json
    - run: mv build-domain/openapi.json build/domain-openapi.json
    - run: mv build-billing/openapi.json build/billing-openapi.json
    - run: mv build-addon/openapi.json build/addon-openapi.json
    - run: node generator.js Auth build/auth-openapi.json build/auth-client.js
    - run: node generator.js Compute build/compute-openapi.json build/compute-client.js
    - run: node generator.js Domain build/domain-openapi.json build/domain-client.js
    - run: node generator.js Billing build/billing-openapi.json build/billing-client.js
    - run: node generator.js Addon build/addon-openapi.json build/addon-client.js
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: build
        FOLDER: build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
