name: Swagger Codegen

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
  build:
    runs-on: ubuntu-latest
    container: swaggerapi/swagger-codegen-cli:latest
    
    steps:
      - run: generate -i ./spec/api-spec.v2.yaml -l swagger
  deploy:
    runs-on: ubuntu-latest
    env:
      REPO: self
      BRANCH: build
      FOLDER: ./spec/
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
     - uses: s0/git-publish-subdir-action@develop
    
    
