name: Build Docs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm i -g redoc-cli@0.13.2
    - run: mkdir docs && mkdir docs/auth && mkdir docs/compute && mkdir docs/domain && mkdir docs/billing
    - run: npx redoc-cli bundle spec/auth-api.v1.0.yaml --options.theme.colors.primary.main=#ac0006
    - run: cp redoc-static.html docs/auth/index.html
    - run: npx redoc-cli bundle spec/compute-api.v1.0.yaml --options.theme.colors.primary.main=#ac0006
    - run: cp redoc-static.html docs/compute/index.html
    - run: npx redoc-cli bundle spec/domain-api.v1.0.yaml --options.theme.colors.primary.main=#ac0006
    - run: cp redoc-static.html docs/domain/index.html
    - run: npx redoc-cli bundle spec/billing-api.v1.0.yaml --options.theme.colors.primary.main=#ac0006
    - run: cp redoc-static.html docs/billing/index.html
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: docs
        FOLDER: docs
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
